import type { Metadata } from 'next';
import { Pretendard } from './fonts';
import './globals.css';
import cn from '@/utils/cn';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={cn(
          Pretendard.className,
          'selection:bg-[#0E5BE7] selection:text-[#FFFFFF]',
        )}
      >
        {children}
      </body>
    </html>
  );
}
